/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author Marcos Vilas Boas
 */
import Classes.Pergunta;
import javax.swing.JOptionPane;
public class jfQuiz extends javax.swing.JFrame {
int msgSaida, xp,xn;
Pergunta pergunta = new Pergunta();
jfInfo info = new jfInfo();
    /**
     * Creates new form jfClasses
     */
    public jfQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtSair = new javax.swing.JButton();
        jbtProx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbLevel = new javax.swing.JLabel();
        jlbPergunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });
        jPanel1.add(jbtSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 372, 80, 32));

        jbtProx.setText("Próximo");
        jbtProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtProxActionPerformed(evt);
            }
        });
        jPanel1.add(jbtProx, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 372, -1, 32));

        jLabel1.setText("Pergunta ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setText("Nivel ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jlbLevel.setText("jLabel3");
        jPanel1.add(jlbLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jlbPergunta.setText("jLabel3");
        jPanel1.add(jlbPergunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
       msgSaida = JOptionPane.showConfirmDialog(null,"Deseja mesmo sair?");
       switch (msgSaida){
           case 0:
               System.exit(0);
               break;
           case 1:
              JOptionPane.showMessageDialog(null, "Cancelado");
              break;
       }
    }//GEN-LAST:event_jbtSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
   
    msgSaida = JOptionPane.showConfirmDialog(null,"Deseja mesmo sair?");
    switch (msgSaida){
           case 0:
               System.exit(0);
                break;
           case 1:
              JOptionPane.showMessageDialog(null, "Cancelado");
              break;
       }
    }//GEN-LAST:event_formWindowClosing

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        xp=1; xn=1;
        jlbPergunta.setText(Integer.toString(xp));        
        pergunta.setLevels(xn);
        jlbLevel.setText(Integer.toString(pergunta.getLevels()));        
        info.setTitle("Informações");
        info.show();
    }//GEN-LAST:event_formComponentShown

    private void jbtProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtProxActionPerformed
        xp++;
        if(xp > 5){
            xp=1;
            xn++;
            
            info.show();
        }
        pergunta.setLevels(xn);
        jlbPergunta.setText(Integer.toString(xp));
        jlbLevel.setText(Integer.toString(pergunta.getLevels()));        
    }//GEN-LAST:event_jbtProxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtProx;
    private javax.swing.JButton jbtSair;
    private javax.swing.JLabel jlbLevel;
    private javax.swing.JLabel jlbPergunta;
    // End of variables declaration//GEN-END:variables
}
